# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdvanceGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JARVIS(object):
    def setupUi(self, JARVIS):
        JARVIS.setObjectName("JARVIS")
        JARVIS.resize(1368, 742)
        self.centralwidget = QtWidgets.QWidget(JARVIS)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(-10, -10, 1441, 781))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("../../Downloads/tuse.png"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.ironman = QtWidgets.QLabel(self.centralwidget)
        self.ironman.setGeometry(QtCore.QRect(1030, 20, 291, 661))
        self.ironman.setText("")
        self.ironman.setPixmap(QtGui.QPixmap("../../Downloads/f889323d87ae92dbd5da3b1193708dc3.gif"))
        self.ironman.setScaledContents(False)
        self.ironman.setObjectName("ironman")
        self.circle2 = QtWidgets.QLabel(self.centralwidget)
        self.circle2.setGeometry(QtCore.QRect(570, 165, 341, 251))
        self.circle2.setText("")
        self.circle2.setPixmap(QtGui.QPixmap("../../Downloads/preview.gif"))
        self.circle2.setScaledContents(True)
        self.circle2.setObjectName("circle2")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(680, 260, 121, 51))
        self.textBrowser_5.setStyleSheet("background:transparent;\n"
"border:transparent;"
"color:white;"
"font-size:20px;")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(50, 565, 230, 51))
        self.textBrowser_4.setStyleSheet("background:transparent;\n"
"border:transparent;"
"color:white;"
"font-size:30px;")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_1.setGeometry(QtCore.QRect(30, 135, 241, 51))
        self.textBrowser_1.setStyleSheet("background:transparent;\n"
"border:transparent;"
"color:white;"
"font-size:30px;")
        self.textBrowser_1.setObjectName("textBrowser_1")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(30, 275, 241, 51))
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border:transparent;"
"color:white;"
"font-size:30px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(30, 415, 241, 51))
        self.textBrowser_3.setStyleSheet("background:transparent;\n"
"border:transparent;"
"color:white;"
"font-size:30px;")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1070, 630, 121, 61))
        self.pushButton.setStyleSheet("background-color: rgb(0, 255, 21);\n"
"font: 75 16pt \"Nirmala UI\";\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1190, 630, 121, 61))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 4);\n"
"font: 75 16pt \"Nirmala UI\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.circle = QtWidgets.QLabel(self.centralwidget)
        self.circle.setGeometry(QtCore.QRect(350, 380, 341, 211))
        self.circle.setText("")
        self.circle.setPixmap(QtGui.QPixmap("../../Downloads/FreshAnyHanumanmonkey-size_restricted (1).gif"))
        self.circle.setScaledContents(True)
        self.circle.setObjectName("circle")
        self.loading = QtWidgets.QLabel(self.centralwidget)
        self.loading.setGeometry(QtCore.QRect(620, 440, 401, 101))
        self.loading.setText("")
        self.loading.setPixmap(QtGui.QPixmap("../../Downloads/T8bahf (1).gif"))
        self.loading.setScaledContents(False)
        self.loading.setObjectName("loading")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_6.setGeometry(QtCore.QRect(70, 699, 291, 31))
        self.textBrowser_6.setStyleSheet("background:transparent;\n"
"border:transparent;"
"color:white;"
"font-size:20px;")
        self.textBrowser_6.setObjectName("textBrowser_6")
        JARVIS.setCentralWidget(self.centralwidget)

        self.retranslateUi(JARVIS)
        QtCore.QMetaObject.connectSlotsByName(JARVIS)

    def retranslateUi(self, JARVIS):
        _translate = QtCore.QCoreApplication.translate
        JARVIS.setWindowTitle(_translate("JARVIS", "J.A.R.V.I.S"))
        self.textBrowser_5.setHtml(_translate("JARVIS", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("JARVIS", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_1.setHtml(_translate("JARVIS", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("JARVIS", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("JARVIS", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("JARVIS", "Run"))
        self.pushButton_2.setText(_translate("JARVIS", "Exit"))
        self.textBrowser_6.setHtml(_translate("JARVIS", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JARVIS = QtWidgets.QMainWindow()
    ui = Ui_JARVIS()
    ui.setupUi(JARVIS)
    JARVIS.show()
    sys.exit(app.exec_())
